per_page: 10
minimum: 3
maximum_name: 50
maximum_email: 50
min_range_phone: 10
max_range_phone: 11
maximum_address: 100
mb: 5
one: 1
two: 2
three: 3
four: 4
five: 5
six: 6
seven: 7
eight: 8
nine: 9
ten: 10
accept_image: "image/jpeg, image/gif, image/png"
